title: "MASFAA"
description: The Montana Association of Student Financial Aid Administrators (MASFAA) is an organization serving the needs of students, institutions of higher education, government agencies, and private funding sources through the coordination of plans and programs for student financial aid.

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
timezone: US/Mountain

kramdown:
  toc_levels: "2"

# modify version numbers below when upgrading bootstrap
# only the assets directory is needed from the bootstrap-sass download
bootstrap-sass: bootstrap-sass-3.3.5
sass:
    sass_dir: /bootstrap-sass-3.3.5/assets/stylesheets
    style: :compressed

exclude:
  - vendor
  - circle.yml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
