baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://www.masfaaonline.org" # the base hostname & protocol for your site
title: "MASFAA"

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
