baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://www.masfaaonline.org" # the base hostname & protocol for your site
title: "MASFAA"
description: The Montana Association of Student Financial Aid Administrators (MASFAA) is an organization serving the needs of students, institutions of higher education, government agencies, and private funding sources through the coordination of plans and programs for student financial aid.

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"

# Build settings
markdown: kramdown

# modify version numbers below when upgrading bootstrap
# only the assets directory is needed from the bootstrap-sass download
bootstrap-sass: bootstrap-sass-3.3.5
sass:
    sass_dir: /bootstrap-sass-3.3.5/assets/stylesheets
    style: :compressed
