# Site settings
title: "MASFAA"
description: The Montana Association of Student Financial Aid Administrators (MASFAA) is an organization serving the needs of students, institutions of higher education, government agencies, and private funding sources through the coordination of plans and programs for student financial aid.

repository: mhesac/www.masfaaonline.org
github:
  url: http://localhost:4000

# https://github.com/benbalter/jekyll-seo-tag#usage
logo: icons/apple-touch-icon-180x180.png

# modify version numbers below when upgrading bootstrap
# only the assets directory is needed from the bootstrap-sass download
bootstrap-sass: bootstrap-sass-3.3.7
sass:
    sass_dir: /bootstrap-sass-3.3.7/assets/stylesheets
    style: :compressed

# Build settings
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

kramdown:
  input: GFM
  hard_wrap: true
  toc_levels: "2"

timezone: US/Mountain

exclude:
  - .rspec
  - .ruby-version
  - circle.yml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - spec
  - vendor
